#!/bin/bash
cd ${APPCENTER_SOURCE_DIRECTORY}
echo APPCENTER_KEY_ALIAS=${APPCENTER_KEY_ALIAS}” > .env
echo APPCENTER_KEYSTORE_PASSWORD=${APPCENTER_KEYSTORE_PASSWORD}” >> .env
echo APPCENTER_KEY_PASSWORD=${APPCENTER_KEY_PASSWORD}” >> .env
echo DATA=${DATA}” >> .env
